clover0/issue-agent

- agent/cli/command_issue.go
- agent/config/config.go
Fixed problem of always trying to read config file on container.
> fix loading config

- agent/cli/common_input.go
- agent/cli/issue_input.go
Make it available to be set log level from CLI input.
> add log_level flag

- .github/workflows/development.yml
- README.md
- agent/cli/common_input.go
- agent/cmd/runner/main.go
- agent/functions/search_files.go
- agent/models/bedrock.go
- agent/models/bedrock_llm_forwarder.go
- agent/models/openai.go
- agent/models/selector.go
- website/docs/configuration/command.md
Migrate to Converse API on AWS Bedrock and support for cross-region inference.
> Update 202501 01 7

- .goreleaser.yaml
> auto release

- agent/models/anthropic_llm_forwarder.go
- agent/models/bedrock_llm_forwarder.go
- agent/models/llm_forwarder.go
- agent/models/openai.go
Improve logging about LLM token usage.
> output LLM token usage on returning from LLM response logging

- agent/config/config.go
- agent/config/default_config.yml
- agent/functions/functions.go
- agent/functions/remove_file.go
- agent/functions/remove_file_test.go
- website/docs/configuration/functions.md
- website/docs/configuration/yaml.md
Add remove_file function to remove file in a working repository.
Use case:
- When refactor, maintenance code with removing files
- When remove unused files
> add remove_file function to remove file in repository

- agent/agent/orchestrator.go
- agent/cli/command_create_pr.go
- agent/cmd/list_functions/main.go
- agent/functions/agithub/github_service.go
- agent/functions/agithub/submit_files_service.go
- agent/go.mod
- agent/go.sum
- agent/loader/github_loader.go
- agent/util/pointer/pointer.go
- Bump go-github v68
- Remove deprecated
> bump go-github v68

- agent/agent/orchestrator.go
- agent/functions/agithub/github_service.go
Introduced a check to verify the existence of the base branch.
I made it possible to provide feedback to the user at an early stage when there is a critical issue.
> add base branch existence check

- agent/agent/orchestrator.go
- agent/config/config.go
- agent/config/default_config.yml
- agent/functions/agithub/submit_files_service.go
- agent/functions/submit_file_service.go
Add feature to add labels to PR created by Issue Agent.
`issue_agent.yml`
```yaml
agent:
github:
pr_labels:
- "issue-agent"
- "other"
- ...
```
> add ability to add labels to PR created by agent

- README.md
- agent/util/aws.go
- website/docs/configuration/models.md
https://www.anthropic.com/news/claude-3-7-sonnet
- Anthropic API
- AWS Bedrock
> support Claude 3.7 Sonnet

- agent/functions/list_files.go
More context can be put into the LLM.
> improve list-files fuction to list recursively

- agent/agent/agent.go
- agent/agent/llm_forwarder.go
- agent/agent/orchestrator.go
- agent/agent/step.go
- agent/cli/command_create_pr.go
- agent/models/anthropic_llm_forwarder.go
- agent/models/bedrock.go
- agent/models/bedrock_llm_forwarder.go
- agent/models/openai.go
- agent/models/openai_llm_forwarder.go
- agent/models/selector.go
- agent/models/selector_test.go
> move steps under agent package

- agent/cli/command_create_pr.go
- agent/core/agent.go
- agent/core/llm_forwarder.go
- agent/core/orchestrator.go
- agent/core/parameter.go
- agent/core/step.go
- agent/core/tools.go
- agent/models/anthropic_llm_forwarder.go
- agent/models/bedrock.go
- agent/models/bedrock_llm_forwarder.go
- agent/models/openai.go
- agent/models/openai_llm_forwarder.go
- agent/models/selector.go
- agent/models/selector_test.go
> rename agent package to core

- agent/core/agent.go
Issue Agent logs.
```
...
[STEP]forwarding message to LLM and waiting for response
...
```
Show step number on the right of `STEP`.
```
...
[STEP:3]forwarding message to LLM and waiting for response
...
```
> show step number

- agent/agithub/github_service.go
- agent/agithub/submit_revision_service.go
- agent/cli/command.go
- agent/cli/command_help.go
- agent/cli/command_react.go
- agent/cli/input_common.go
- agent/cli/input_react.go
- agent/cmd/list_functions/main.go
- agent/config/default_config.yml
- agent/core/functions/functions.go
- agent/core/functions/get_pull_request.go
- agent/core/functions/submit_revision.go
- agent/core/functions/submit_revision_service.go
- agent/core/orchestrator.go
- agent/core/prompt/prompt_builder.go
- agent/core/prompt/prompt_en.yml
- agent/core/tools.go
`react` reacts a comment on GitHub Pull Request. 
After creating a pull request  by Issue Agent, for minor modifications, we comment to pull request and direct to agent from comment.
Usage:
```
issue-agent react OWNER/REPO/issues/comments/COMMENT_ID
```
Example:
```
issue-agent react clover0/example-repo/issues/comments/2710395903
```
> implement react command feature

- website/docs/configuration/command.md
- website/docs/configuration/functions.md
- website/docs/getting-started/use-cases.md
update documentation new feature. https://github.com/clover0/issue-agent/pull/193
> update website to keep up with new feature

- agent/agithub/submit_files_service.go
- agent/agithub/submit_revision_service.go
Error caused When agent remove file on creating PR or change commit.
> fix lstat deleted file error

- agent/config/default_config.yml
Fix error:
```
error running agent: yaml: unmarshal errors:
line 57: cannot unmarshal !!str `` into []string
line 60: cannot unmarshal !!str `` into []string
exit status 1
```
> fix error on parsing default config

- agent/core/agent.go
- agent/logger/color.go
When error caused after executing functions, print error log.
> improve error logging visibility

- agent/agithub/github_service.go
- agent/core/functions/get_pull_request.go
- agent/core/prompt/prompt_builder.go
- agent/core/prompt/prompt_en.yml
Enhance prompt.
Add issue's title to prompt.
> add issue titles to prompts and related functions

- renovate.json5
> Set rangeStrategy to bump

- agent/core/functions/get_issue.go
`repository` does not exist in `get_issue` function arguments.
> fix required parameter of get_issue

- agent/agithub/submit_files_service.go
- agent/core/functions/switch_branch.go
Fixed an error when pushing a branch if the remote base branch is updated after creating a git branch from base.
> fix error when pushing a branch

- agent/agithub/github_service.go
- agent/config/default_config.yml
- agent/core/functions/functions.go
- agent/core/functions/get_pull_request.go
- agent/core/functions/get_repository_content.go
- agent/core/tools.go
- website/docs/configuration/command.md
- website/docs/configuration/functions.md
- website/docs/getting-started/use-cases.md
- website/mkdocs.yml
This function retrieves file or directory contents from a specified GitHub repository. It enables enhanced use cases like loading review guidelines for code reviews.
> add `get_repository_content` function

- agent/core/functions/get_pull_request.go
- agent/core/functions/github_service.go
> separate to interface file

- README.md
- agent/models/anthropic_llm_forwarder.go
- agent/models/bedrock.go
- agent/models/claude.go
- agent/models/claude_test.go
- agent/util/aws.go
Support for Claude 4 Sonnet, Claude 4 Opus models.
> add support for Claude 4

- agent/core/prompt/prompt_en.yml
Updated prompts to enhance clarity, emphasizing environment constraints and file size handling. Removed redundant sections.
> refine prompts and remove redundant templates

- agent/core/agent.go
Prefixed logger with step labels to improve traceability during function execution.
> enhance logging context in function execution

- agent/core/llm_forwarder.go
- agent/models/anthropic_llm_forwarder.go
- agent/models/bedrock.go
- agent/models/bedrock_llm_forwarder.go
- agent/models/claude.go
* Bedrock Converse API prompt caching
https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-caching.html
* Anthropic Claude 
https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching
> Enable prompt cache for Bedrock and Anthropic API
